# Generated by Django 4.2.21 on 2025-05-30 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('prediction', models.TextField(verbose_name='Предсказание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Расклад',
                'verbose_name_plural': 'Расклады',
            },
        ),
        migrations.CreateModel(
            name='TarotCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название карты')),
                ('image', models.ImageField(upload_to='tarot_cards/', verbose_name='Изображение карты')),
            ],
            options={
                'verbose_name': 'Карта Таро',
                'verbose_name_plural': 'Карты Таро',
            },
        ),
        migrations.CreateModel(
            name='DrawnCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reversed', models.BooleanField(default=False, verbose_name='Перевернутая')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predict.tarotcard')),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawn_cards', to='predict.reading')),
            ],
            options={
                'verbose_name': 'Выпавшая карта',
                'verbose_name_plural': 'Выпавшие карты',
            },
        ),
    ]
